# FactionsScoreboard
# v 1.0
# Official FileConfiguration

scoreboard:
  enabled: true
  map:
    size: 7  # This must be an odd number!  This number should not be over 7 to prevent each line from being too long.
    center: "    "  # This will add spaces to the left of the map (to center it).  4 spaces will usually center it.
    default_center: "   "  # This is the same as the above option but for THE DEFAULT NO FACTION BOARD.
    char: "▇"  # The char that will be shown on the map for each chunk
    colors:
      you: "&8"
      wilderness: "&7"
      your_faction: "&a"
      ally: "&d"
      enemy: "&4"
      neutral: "&5"

  title:
    no_faction: "&8< &7Factions &c&lRED &8>"
    faction: "&8< &c&n{FACTION}&8 > "
  prefixes:
    recruit: "&7"
    officer: "&c✩ &7"
    co-leader: "&c✩✩ &7"
    admin: "&4✩✩✩&7 "  # This is leader, factionsuuid just has cucked roles :/
  faction_lines:
    - ""
    - "&eMap &8> "
    - "{MAP}"
    - "&eOnline Members &8>"
    - "{MEMBERS}"
  default_lines:
    - ""
    - "{MAP}"
    - ""
    - "&7No &c&nFaction&7"

messages:
  enabled: "&7FactionsScoreboard &aenabled&7!"
  disabled: "&7FactionsScoreboard &cdisabled&7!"
